# Generated by Django 4.2.8 on 2025-12-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Automatically generated from video at 5 seconds if not uploaded.', null=True, upload_to='thumbnails/'),
        ),
    ]
